name: simple_dart_api
version: 0.0.1
description: SimpleDartAPI is a Dart Framework that will allow you to easily create your own API in Dart.
author: Corentin Pillet
homepage: https://github.com/Kordam/SimpleDartAPI
dependencies:
  browser: any
  logging: '>=0.9.1+1 <0.10.0'
  route: any
  yaml: 1.1.1
